### ISSUE TITLE
Package gnupg2 not available on Ubuntu20.04

### ISSUE THREAD

**Issue by 24367dfa** [geerlingguy/ansible-role-docker#263]
On current Ubuntu 20.04 LTS distributions the `gnupg2` package seems to be unavailable/replaced by `gnupg`.

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

```bash
$ sudo apt install gnupg2
[...]
Package gnupg2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available form another source
However the following packages replace it:
  gpgv gpgsm gnupg-l10n gnupg dirmngr
```

**Comment by toxinu** [comment]
Pull request: https://github.com/geerlingguy/ansible-role-docker/pull/268

**Comment by 24367dfa** [comment]
Fixed in #268

**Comment by stevefan1999-personal** [comment]
I request reopening it since it regresses on Debian Buster. @geerlingguy 

![image](https://user-images.githubusercontent.com/29133953/124414651-b57a1d80-dd85-11eb-86e6-d22b4c0a27b9.png)

**Comment by stevefan1999-personal** [comment]
@24367dfa it's just me forgetting to run apt update before installing gnupg2 package, since the newly baked Buster Vagrant image does not have the latest apt cache available (for image slimming of course). so it is actually an user error.
Just add this in pre_tasks:
```yaml
    - name: Run apt update before installing prerequisites
      apt:
        update_cache: yes
```

**Comment by yusmpgroup** [comment]
Still not possible to install on 20.04. This is fun how they call it LTS but everything literally stops working with each new Ubuntu release...

```
sudo apt install dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 1password : Depends: gnupg2 but it is not going to be installed
             Recommends: libappindicator1 but it is not going to be installed
 dkms : Depends: dctrl-tools
E: Unmet dependencies.
```
